LEFT_HAND:
- ACTION_NAME: close
  POSITION:
  - 67
  - 151
  - 0
  - 0
  - 0
  - 0
  - 37
- ACTION_NAME: open
  POSITION:
  - 255
  - 179
  - 255
  - 255
  - 255
  - 255
  - 83
RIGHT_HAND:
- ACTION_NAME: close
  POSITION:
  - 67
  - 151
  - 0
  - 0
  - 0
  - 0
  - 37
- ACTION_NAME: open
  POSITION:
  - 255
  - 179
  - 255
  - 255
  - 255
  - 255
  - 83
